load all apps for an organization
openlattice/conductor-client pull request #940
Opened 2020-09-04 21:25 UTC by katherinebernstein

2020-09-04 22:11 UTC, geekbeast approved these changes

2020-09-14 15:59 UTC, makosblade approved these changes

2020-09-14 23:46 UTC, geekbeast commented on src/main/kotlin/com/openlattice/apps/services/AppService.kt
> +            roleMappings.forEach { (roleId, roleAclKey) ->
Make sure the map itself is always serializable. Had problems in Organization Service when folks were passing in a map that wasn't serializable.

2020-09-14 23:48 UTC, geekbeast requested changes

2020-09-14 23:48 UTC, geekbeast commented on src/main/kotlin/com/openlattice/apps/services/AppService.kt
> +        val missingRoleIds = Sets.difference(roleIds, app.appRoles.map { it.id }.toSet())
roleIds  - app.appRoles, the view created by Sets.difference is expensive and you have to create another set by calling .toSet() anyway.

2020-09-15 04:05 UTC, UnsungHero97 approved these changes

2020-09-15 04:12 UTC, geekbeast approved these changes

2020-09-15 04:12 UTC, merged